### ISSUE TITLE
Write AngularJS Tutorials

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Codev#1]
Curate or write AngularJS Tutorials on the following subjects:
* `Introduction to AngularJS`
* `Your First Project`
Write about how to get started using angular, start from scratch and create a simple app (preferably not a todo app)
* `Why Choose Angular`
With the ever increasing number of JavaScript frameworks talk about what advantages Angular has. For example, it is backed by Google, well-documented and well-maintained.

**Comment by disisisid** [comment]
Just to clarify, do you need AngularJS(1.x) tutorials as well or just Angular(2+)?

**Comment by maaslalani** [comment]
@disisisid Angular (2+) is good.
