### ISSUE TITLE
Write React Tutorials

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Codev#2]
Curate or write ReactJS Tutorials on the following subjects:
* `Getting started with React`
* `Your First Component`
Walk through creating a simple component and build up in complexity.
* `Why Choose React`
With the ever increasing number of JavaScript frameworks talk about what advantages React has. For example, it is backed by Facebook, well-documented and well-maintained.

**Comment by aquibbaig** [comment]
can i take up the issue?

**Comment by Harkindey** [comment]
@aquibbaig i dont think the task is just for one person, it's for everyone. correct @maaslalani ?

**Comment by maaslalani** [comment]
Yep! It's for everyone. I want to make Codev an open-sourced and self-managed tutorial website, where developers can give back to the community by writing tutorials.

**Comment by maaslalani** [comment]
Just write as much as you guys can, if you come up with more tutorials ideas add those as well!
@Harkindey @aquibbaig
