### ISSUE TITLE
Write Python Tutorials

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Codev#3]
Write or curate Python tutorials (writing is preferred over curation however please ensure the quality of the tutorial is very high)
* `Basic Syntax`
* `Classes in Python`
* `The Pythonic Way`

**Comment by jon-chiou** [comment]
I'll work on the Basic Syntax tutortial

**Comment by kabollinger** [comment]
It can't hurt to brush up on Classes myself. I'll take that one.
