### ISSUE TITLE
Write Javascript Tutorials

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Codev#4]
Write (or curate) one or more tutorials on Javascript. Please ensure quality of tutorial is high for it to be merged.
* `Beginner's Guide`
Introduction to Javascript.

* `Basic Syntax`

* `Replacing JQuery`
http://youmightnotneedjquery.com/

**Comment by deepanjali19** [comment]
Hello @maaslalani I would like to contribute to your repository by adding JavaScript tutorials. 
It will be great if you can elaborate more on what you are expecting for "Replacing JQuery" section.
In the mean time, I will writing the JavaScript tutorials.

**Comment by maaslalani** [comment]
@deepanjali19 Many people use `Jquery` since it's easier to learn than Vanilla `JavaScript` this tutorial would be for people who already know `JQuery` but want to stop using it and opt for Vanilla `JavaScript` instead.

**Comment by deepanjali19** [comment]
Got it! Thank you @maaslalani for the clarification. I am working on this issue and will create a pull request soon. 👍
