### ISSUE TITLE
Write Git tutorials

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Codev#5]
Please write or curate tutorials on Git. Ensure quality is high to be merged.
* `Setup Guide`
How to get setup
* `Using Version Control`
Why we should use it, why its useful.
* `Advanced Features`
Cool tips and tricks for advanced users

**Comment by alisyahidin** [comment]
i think i can do this, :smiley:

**Comment by alisyahidin** [comment]
Hi @maaslalani , i've create tutorials about git #7 . If you like it, i will continue to create the tutorial.
